rm(list=ls())
library(Lahman)
library(retrosheet)
library(dplyr)
library(ggplot2)
library(ggthemes)

perfectgames <- read.csv('gamedata.csv', stringsAsFactors = FALSE)

pitching.tmp <- Master %>%
  select(playerID, nameFirst, nameLast, retroID) %>%
  inner_join(Pitching, by = 'playerID') %>%
  filter(nameFirst %in% perfectgames$nameFirst &
           nameLast %in% perfectgames$nameLast &
           yearID %in% perfectgames$year)

pitcherstats <- data.frame(NULL)

for(i in 1:nrow(perfectgames)) {
  pitcherstats <- rbind(pitcherstats,
                        filter(pitching.tmp, nameFirst == perfectgames$nameFirst[i],
                               nameLast == perfectgames$nameLast[i],
                               yearID == perfectgames$year[i]))
}

pitcherstats <- mutate(pitcherstats, OBA = 1-(H+BB+HBP)/BFP)
pitcherstats <- inner_join(pitcherstats, perfectgames[ ,c('nameLast','year','date')], by = c('yearID'='year', 'nameLast'='nameLast'))

write.csv(pitcherstats, "perfectPitch.csv")

batterdata <- read.csv('batterdata.csv', stringsAsFactors = FALSE)

batting.tmp <- Master %>%
  select(playerID, nameFirst, nameLast, retroID) %>%
  inner_join(Batting, by = 'playerID') %>%
  filter(nameFirst %in% batterdata$nameFirst &
           nameLast %in% batterdata$nameLast &
           yearID %in% batterdata$year)

batterstats <- data.frame(NULL)
pitchers <- c()

for(i in 1:nrow(perfectgames)) {
  batters <- batterdata[batterdata$pitcher == perfectgames$nameLast[i], ]
  numBatters <- 0
  for(j in 1:nrow(batterdata)) {
    b <- filter(batting.tmp, nameFirst == batters$nameFirst[j] &
                  nameLast == batters$nameLast[j] &
                  yearID == batters$year[j])
    batterstats <- rbind(batterstats, b)
    numBatters <- numBatters + nrow(b)
  }
  pitchers <- c(pitchers, rep(perfectgames$nameLast[i], numBatters))
}
batterstats <- cbind(batterstats, pitcher=pitchers)

batterstats <- batterstats %>% group_by(playerID, nameFirst, nameLast, yearID) %>%
  summarize(H=sum(H), BB=sum(BB), HBP=sum(HBP), AB=sum(AB), SF=sum(SF), pitcher=first(pitcher))
batterstats$SF[is.na(batterstats$SF)] <- 0

batterstats <- mutate(batterstats, OBP = (H+BB+HBP)/(AB+BB+HBP+SF))

batterstats <- read.csv('perfectBatter.csv', stringsAsFactors = FALSE)

allstats <- inner_join(batterstats[ ,c('playerID','nameFirst','nameLast','yearID','OBP','pitcher')],
                       pitcherstats[ ,c('nameLast','yearID','OBA')],
                       by = c('pitcher'='nameLast', 'yearID'='yearID')) %>%
  mutate(odds=OBP/(OBP+OBA)) %>%
  inner_join(batterdata[ ,c('nameFirst','nameLast','year','AB')],
             by = c('nameFirst'='nameFirst','nameLast'='nameLast','yearID'='year'))

### Start here with 'perfectPitchAll.csv' ###


allstats <- read.csv('perfectPitchAll.csv', stringsAsFactors = FALSE)

probs <- group_by(allstats, yearID, pitcher) %>%
  summarize(p = prod((1-odds)^AB)) %>%
  arrange(yearID)

write.csv(probs, "perfectProbs.csv")

probs$pitcher <- as.factor(probs$pitcher)
probs$pitcher <- factor(probs$pitcher, levels(probs$pitcher)[as.numeric(probs$pitcher)])
ggplot(probs, aes(x=pitcher, y=p)) +
  geom_bar(stat='identity', fill='slategray2') +
  theme(axis.text.x = element_text(size = 10,
                                   angle = 45,
                                   hjust = 1,
                                   vjust = 1))


probs$pitcher<-reorder(probs$pitcher,probs$p)

ggplot(probs, aes(x=pitcher, y=p)) +
  geom_bar(stat='identity', aes(fill=probs$p), show.legend = FALSE) +
  labs(x = "Pitcher", y="Perfect Game Probability", title = "Greatest Perfect Games", subtitle = "All perfect games since 1900 ranked using probabilities generated by the Bradley-Terry method", fill="Probability") +
  theme(axis.text.x = element_text(size = 10,
                                   angle = 45,
                                   hjust = 1,
                                   vjust = 1))

mean(allstats$OBA)  
mean(allstats$OBP)

order <- read.csv('perfectOrder16-21.csv', stringsAsFactors = FALSE)

orderYoung <- order[order$Pitcher=="Young",]

orderJoss <- order[order$Pitcher=="Joss",]

orderBarker <- order[order$Pitcher=="Barker",]

orderHernandez <- order[order$Pitcher=="Hernandez",]

orderBrowning <- order[order$Pitcher=="Browning",]

orderKoufax <- order[order$Pitcher=="Koufax",]

ggplot(orderYoung, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Cy Young", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderJoss, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Addie Joss", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderBarker, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Len Barker", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderHernandez, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Felix Hernandez", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderBrowning, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Tom Browning", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderKoufax, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Sandy Koufax", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

order <- read.csv('perfectOrder11-15.csv', stringsAsFactors = FALSE)

orderWitt <- order[order$Pitcher=="Witt",]

orderBunning <- order[order$Pitcher=="Bunning",]

orderHalladay <- order[order$Pitcher=="Halladay",]

orderCain <- order[order$Pitcher=="Cain",]

orderWells <- order[order$Pitcher=="Wells",]

ggplot(orderWitt, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Mike Witt", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderBunning, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Jim Bunning", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderHalladay, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Roy Halladay", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderCain, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Matt Cain", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderWells, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "David Wells", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

order <- read.csv('perfectOrder6-10.csv', stringsAsFactors = FALSE)

orderHunter <- order[order$Pitcher=="Hunter",]

orderRogers <- order[order$Pitcher=="Rogers",]

orderJohnson <- order[order$Pitcher=="Johnson",]

orderMartinez <- order[order$Pitcher=="Martinez",]

orderHumber <- order[order$Pitcher=="Humber",]

ggplot(orderHunter, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Catfish Hunter", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderRogers, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Kenny Rogers", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderJohnson, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Randy Johnson", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderMartinez, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Dennis Martinez", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderHumber, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Phillip Humber", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

aggregate(batterstats[, 12], list(batterstats$pitcher), mean)

order <- read.csv('perfectOrder1-5.csv', stringsAsFactors = FALSE)

orderBraden <- order[order$Pitcher=="Braden",]

orderCone <- order[order$Pitcher=="Cone",]

orderLarsen <- order[order$Pitcher=="Larsen",]

orderBuehrle <- order[order$Pitcher=="Buehrle",]

orderRobertson <- order[order$Pitcher=="Robertson",]

ggplot(orderBraden, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Dallas Braden", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderCone, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "David Cone", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderLarsen, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Don Larsen", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderBuehrle, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.45)) +
  labs(x = "Batter Number", y="OBP", title = "Mark Buehrle", subtitle = "Batters Faced OBP Progression") + ylim(.05, .45)

ggplot(orderRobertson, aes(x=BatterNum, y=OBP)) +
  geom_line(stat='identity', size=.5, show.legend = FALSE) + geom_point(aes(color=OBP),size=4, show.legend = FALSE) + scale_color_gradient(low ="green3", high ="red2", limits=c(.05,.47)) +
  labs(x = "Batter Number", y="OBP", title = "Charlie Robertson", subtitle = "Batters Faced OBP Progression") + ylim(.05, .47)
